package lexer;

public enum TokenType {
    // Keywords
    VAR, TYPE, IS, END, INTEGER, REAL, BOOLEAN, TRUE, FALSE, RECORD,
    ARRAY, WHILE, LOOP, FOR, IN, REVERSE, IF, THEN, ELSE, ROUTINE,
    AND, OR, NOT, XOR, PRINT, RETURN,

    // Operators
    RANGE, ADD, MINUS, MULTIPLY, DIVIDE, REMAINDER,
    RBRACKET, LBRACKET, LESS, LEQUALS, GREATER, GEQUALS,
    EQUALS, NEQUALS, DOT, COMMA, ASSIGN, COLON, LPAREN, RPAREN,
    SLCOMMENT, MLCOMMENT_START, MLCOMMENT_END,

    //Literals
    IDENTIFIER, INTEGER_LITERAL, REAL_LITERAL,

    // Special Tokens
    SEPARATOR, EOF, ILLEGAL
}
